name: Lagerbestand automatisch abgleichen

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: PHP installieren
        run: sudo apt-get update && sudo apt-get install php -y

      - name: update_lager.php ausführen
        run: php update_lager.php
